name: Dump GitHub Context

on:
  # Allows you to click a button to run this manually
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  debug_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        # Piping to 'jq .' makes the output colorful and formatted
        run: echo "$GITHUB_CONTEXT" | jq .