name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run unit tests
        run: npm run test
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Create production build
        run: npm run build
      - name: Deploy to Fly.io
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Discord notifications in case of success/failure
      - name: Build Failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # Fallback to github.actor if head_commit is missing (PRs)
          AUTHOR: ${{ github.event.head_commit.author.username || github.actor }}
          # Fallback to the repo URL/commit SHA for PRs
          COMMIT_URL: ${{ github.event.head_commit.url || github.event.pull_request.html_url }}
        run: |
          curl -X POST $DISCORD_WEBHOOK \
          -H "Content-Type: application/json" \
          -d '{
            "username": "GitHub Actions",
            "content": "Build Failed",
            "embeds": [{
              "description": "commit '"$COMMIT_URL"' by '"$AUTHOR"' broke the build :(",
              "color": 16711680
            }]
          }'

      - name: Deploy Success
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST $DISCORD_WEBHOOK \
          -H "Content-Type: application/json" \
          -d '{
            "username": "${{ github.event.head_commit.author.username }}",
            "content": "A new version of Pokedex deployed",
            "embeds": [{
              "description": "to https://pokedex-6722.fly.dev",
              "color": 65280
            }]
          }'

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      # You must checkout code here so the action can read git history
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Recommended for versioning actions to see full history
      
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          # DRY_RUN: true
