name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run unit tests
        run: npm run test
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Create production build
        run: npm run build
      - name: Deploy to Fly.io
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Discord notifications in case of success/failure
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            text: Test Failed!
            description: commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build >:(
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deploy Success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        with:
            severity: info
            text: A new version of Pokedex deployed!
            description: to https://pokedex-6722.fly.dev by ${{ github.event.head_commit.author.username}}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      # You must checkout code here so the action can read git history
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Recommended for versioning actions to see full history
      
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          # DRY_RUN: true
